version: "3.2"

services:
  posts-api:
    build:
      context: .
    image: frishi/posts-service-api
    container_name: posts-service-api
    env_file: docker-compose.env
    environment:
      SERVICES: posts-api
      PORT: 5000
    depends_on: 
      - mongo
    external_links:
      - nats
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=posts-api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
    networks:
      - internal
      - analytics-service_internal

  posts:
    build:
      context: .
    image: frishi/posts-service
    container_name: posts-service
    env_file: docker-compose.env
    environment:
      SERVICES: posts
    ports:
      - 3060:3060 
    depends_on: 
      - mongo
    labels:
      - "traefik.enable=false"
    external_links:
      - nats
      - redis
    networks:
      - internal
      - analytics-service_internal
  
  mongo:
    image: mongo
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb/:/data/db
    networks:
      - internal

networks:
  internal:
  analytics-service_internal:
    external: true
