version: "3.2"

services:
  posts-api:
    build:
      context: ./
    image: frishi/posts-service-api
    container_name: posts-service-api
    env_file: docker-compose.env
    environment:
      SERVICES: posts-api
      PORT: 5000
    external_links:
      - nats
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=posts-api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
    networks:
      - internal

  posts:
    build:
      context: ./
    image: frishi/posts-service
    container_name: posts-service
    env_file: docker-compose.env
    environment:
      SERVICES: posts 
    labels:
      - "traefik.enable=false"
    external_links:
      - nats
      - redis
      - traefik
    networks:
      - internal

networks:
  internal:
