version: "3.3"

services:
  posts-api:
    build:
      context: .
    image: frishi/posts-service-api
    container_name: posts-service-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 5000
    depends_on: 
      - mongo
    ports:
      - "5000:5000"
    external_links:
      - nats
      - traefik
    labels:
      - traefik.http.routers.posts-api.service=posts-api@docker
      - traefik.http.services.posts-api.loadbalancer.server.port=5000
      - traefik.enable=true
      - traefik.docker.network=gateway
      # - traefik.http.routers.posts-api.rule=Host(`localhost`) && PathPrefix(`/api/v1/posts/`)
      - traefik.http.routers.posts-api.rule=Host(`services.rishighan.com`) && PathPrefix(`/api/v1/posts/`)
      - traefik.http.routers.posts-api.entrypoints=websecure
      - traefik.http.routers.posts-api.tls=true
      - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
      - traefik.http.routers.posts-api.middlewares=https_redirect
      - traefik.http.routers.posts-api.tls.certresolver=le
    networks:
      - gateway 

  posts:
    build:
      context: .
    image: frishi/posts-service
    container_name: posts-service
    env_file: docker-compose.env
    environment:
      SERVICES: posts
    depends_on: 
      - mongo
    labels:
      - traefik.enable=false
    external_links:
      - nats
    networks:
      - gateway 
  
  mongo:
    image: mongo
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb/:/data/db
    labels:
      - traefik.enable=false
    networks:
      - gateway

networks:
  gateway:
    external: true
