version: "3.2"

services:
  posts-api:
    build:
      context: .
    image: frishi/posts-service-api
    container_name: posts-service-api
    env_file: docker-compose.env
    environment:
      SERVICES: posts-api
      PORT: 5000
    depends_on: 
      - mongo
    external_links:
      - nats
      - traefik
    labels:
      - traefik.http.services.posts-api.loadbalancer.server.port=5000
      - traefik.enable=true
      - traefik.docker.network=rgnetwork
      - traefik.http.routers.posts-api.rule=Host(`services.rishighan.com`) && PathPrefix(`/`)
    networks:
      - rgnetwork 

  posts:
    build:
      context: .
    image: frishi/posts-service
    container_name: posts-service
    env_file: docker-compose.env
    environment:
      SERVICES: posts
    depends_on: 
      - mongo
    labels:
      - traefik.enable=false
    external_links:
      - nats
      - redis
    networks:
      - rgnetwork 
  
  mongo:
    image: mongo
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb/:/data/db
    labels:
      - traefik.enable=false
    networks:
      - rgnetwork

networks:
  rgnetwork:
    external: true
