version: "3.3"

services:
  posts-api:
    build:
      context: .
    image: frishi/posts-service-api
    container_name: posts-service-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 5000
    depends_on: 
      - mongo
      - caddy
    external_links:
      - nats
    networks:
      - gateway 

  posts:
    build:
      context: .
    image: frishi/posts-service
    container_name: posts-service
    env_file: docker-compose.env
    environment:
      SERVICES: posts
    depends_on: 
      - mongo
    external_links:
      - nats
    networks:
      - gateway 
  
  mongo:
    image: bitnami/mongodb
    container_name: db
    restart: always
    env_file: docker-compose.env
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb/:/bitnami/mongodb
    networks:
      - gateway

networks:
  gateway:
    external: true
